## Introduction to TensorFlow

### What is TensorFlow?
TensorFlow is an open-source machine learning framework developed by Google Brain. It is widely used for deep learning, neural networks, and AI research. TensorFlow provides a flexible ecosystem to build, train, and deploy machine learning models efficiently.

### Why Use TensorFlow?
- **Scalability:** Works on CPUs, GPUs, and TPUs (Tensor Processing Units).
- **Flexibility:** Supports neural networks, traditional ML algorithms, and even reinforcement learning.
- **Production-Ready:** Can be used for deploying models on the cloud, edge devices, and mobile apps.
- **Support for Multiple Languages:** Primarily supports Python, but also has APIs for C++, Java, and JavaScript.

### Key Features of TensorFlow
1. **Tensor-Based Computation**
  - The name TensorFlow comes from "Tensors" (multi-dimensional arrays) that flow through operations.
  - Supports automatic differentiation for optimization (via tf.GradientTape).
2. Keras API for High-Level ML
  - Keras (`tf.keras`) is a user-friendly high-level API built on TensorFlow for deep learning.
  - Supports both sequential and functional API models.
3. TensorFlow Datasets & Data Pipelines
  - `tf.data API` Handles large-scale datasets efficiently.
  - `tf.keras.preprocessing` Helps in data augmentation and pre-processing.
4. GPU Acceleration
  - Automatically runs computations on GPUs when available for faster training.
5. Deployment & Serving
  - TensorFlow Serving – Deploy trained models as web services.
  - TensorFlow Lite – Optimized for mobile and embedded devices.
  - TensorFlow.js – Runs ML models in web browsers.


## Introduction to Tensors

Tensors are the fundamental data structures in deep learning. They serve as the primary way of representing and processing data in neural networks. Understanding tensors is crucial because deep learning frameworks like TensorFlow and PyTorch use them extensively.

### What is a Tensor?
A tensor is a generalization of scalars, vectors, and matrices to higher dimensions. It is a multi-dimensional array that can store numerical data. You can think of tensors as an extension of arrays in NumPy but optimized for deep learning tasks.

| Tensor Type       | Description                    | Example                        |
|-------------------|--------------------------------|--------------------------------|
| **Scalar (0D)**   | A single number               | `x = 5`                        |
| **Vector (1D)**   | A 1D array of numbers         | `[1, 2, 3]`                    |
| **Matrix (2D)**   | A 2D array (rows & columns)   | `[[1, 2], [3, 4]]`             |
| **3D Tensor**     | A collection of matrices      | `[[[1,2], [3,4]], [[5,6], [7,8]]]` |
| **n-D Tensor**    | A general n-dimensional array | Used in complex DL models      |


In deep learning, tensors are used to represent:

- **Input Data** (e.g., images, text, audio)
- **Weights & Biases** of neural networks
- **Intermediate Computations** in forward and backward passes

The very first and major library to be imported is `tensorflow` for which `tf` is a common alias.

In [1]:
import tensorflow as tf

In [3]:
# Create a scalar (0D)
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
# check the number of dimensions
scalar.ndim

0

In [16]:
# Create a vector (1D)
vector = tf.constant([1, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

In [7]:
# Check dimenstions
vector.ndim

1

In [15]:
# Create a matrix (2D)
matrix = tf.constant([[6, 4],
                      [8, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [ 8, 10]], dtype=int32)>

In [10]:
# Check dimension
matrix.ndim

2

As you have probably noticed so far, TensorFlow generates tensors of type either `int32` or `float32` by default. However, you can decrease it to 16 if you wish.
**NOTE!** The higher the value, the more space it takes up on your computer.

In [17]:
# Create matrix 2 ans specidy the data type explicitly
matrix2 = tf.constant([[5., 5.],
                        [4., 4.],
                        [6., 6.]], dtype=tf.float16) # datatype specified
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 5.],
       [4., 4.],
       [6., 6.]], dtype=float16)>

In [19]:
# Let us create a tensor? (3D and above)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [9, 8, 7]],
                      [[6, 5, 4],
                       [3, 2, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]],

       [[6, 5, 4],
        [3, 2, 1]]], dtype=int32)>

In [20]:
tensor.ndim

3

### Creating Tensors with `tf.Variable()` in TensorFlow
`tf.Variable()` is used to create mutable tensors in TensorFlow, meaning their values can be changed during training. Unlike `tf.constant()`, which creates immutable tensors, `tf.Variable()` allows modifications, making it useful for model parameters like weights and biases. Balow you can see the basic usage of `tf.Variable()`:

In [24]:
# Create a tensor variable
variable_tensor = tf.Variable([1, 2, 3], dtype=tf.float32)
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


### Changing the Value of `tf.Variable`
`assign()` updates the variable in place. You can also modify specific elements.

In [25]:
# Change the values of the variable
variable_tensor.assign([4, 5, 6])
print(variable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>


**NOTE!** You cannot modify the elements of a tensor in similar way as you normally do with lists e.g., `changeable_tensor[0] = 7`. It will surely raise an error.

You can also modify specific elements:

In [27]:
# Add 1 to each element
variable_tensor.assign_add([1, 1, 1])

print(variable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([6., 7., 8.], dtype=float32)>


Key Differences between `tf.Variable()` and `tf.constant()`:

| Feature         | `tf.Variable()` | `tf.constant()` |
|----------------|---------------|---------------|
| **Mutable?**   | ✅ Yes | ❌ No |
| **Trainable?** | ✅ Yes (for model parameters) | ❌ No |
| **Use Case**   | Weights, biases, dynamic tensors | Fixed tensors, constants |


### Creating Random Tensors in TensorFlow
In TensorFlow, you can create random tensors using functions from the `tf.random` module. Random tensors are useful for initializing neural network weights, data augmentation, and stochastic processes.

In [36]:
# Create a random tensor with shape (3, 2)
random_tensor = tf.random.normal(shape=(3, 2))
print(random_tensor)

tf.Tensor(
[[ 0.08422458 -0.86090374]
 [ 0.37812304 -0.00519627]
 [-0.49453196  0.6178192 ]], shape=(3, 2), dtype=float32)


In [30]:
# Create a random tensor drawn from a uniform distribution with shape (3, 2)
tf.random.uniform(shape=(3, 2), minval=0, maxval=10, dtype=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[4.2172585, 2.6803505],
       [6.876185 , 8.206529 ],
       [3.156345 , 6.9819355]], dtype=float32)>

In the tensor above, values are drawn from a uniform distribution between 0 and 10.

In [34]:
# Create a random tensor of integer values drawn from a uniform distribution with shape (3, 2)
tf.random.uniform(shape=(3, 2), minval=0, maxval=100, dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[29, 57],
       [96, 59],
       [24, 70]], dtype=int32)>

In [33]:
# Create a random tensor of binary values drawn from a uniform distribution with shape (3, 2)
tf.random.uniform(shape=(3, 2), minval=0, maxval=2, dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 0],
       [1, 1]], dtype=int32)>

You can also set a random seed for the purpose of reproducibility, i.e., every time you run the code below, you wll obtain a tensor with the exact same values. In other words, if you set a seed you will get the same random numbers every single time. This is similar to `np.random.seed(42)` in NumPy.

In [39]:
tf.random.set_seed(42)  # set the seed
randtens = tf.random.normal(shape=(3, 2))
randtens

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519],
       [-2.3880599, -1.0392479]], dtype=float32)>

There exists a method through which you can shuffle the values in a previously created **variable tensor**: `tf.random.shuffle()`

In [40]:
# shuffle the values in the random varibale tensor created above
shuffled_randtens = tf.random.shuffle(randtens)
shuffled_randtens

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-2.3880599, -1.0392479],
       [ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519]], dtype=float32)>

### Other Ways to Create Tensors in TensorFlow
In TensorFlow, you can create tensors using various methods, including constants, sequences, and random values.

In [41]:
# from numpy array
import numpy as np
numpy_arr = np.arange(1, 25, dtype=np.int32)
A = tf.constant(numpy_arr)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [42]:
# all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [43]:
# all ones
tf.ones(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [44]:
# a tensor with a specific value
tf.fill(dims=(3, 4), value=7)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]], dtype=int32)>

In [46]:
# a tensor with a sequences (range of values)
tf.range(start=1, limit=10, delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [48]:
# a tensor with a sequences (linearly spaced values)
tf.linspace(start=0.0, stop=1.0, num=5)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)>

In [49]:
# identity matrix
tf.eye(num_rows=3, num_columns=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### Get Basic Information About a Tensor
To get information from tensors in TensorFlow (or PyTorch), you can extract key attributes and values using built-in methods. Here's how:

In [52]:
print(f"Shape of the tenso: {randtens.shape}")  # Returns the shape (dimensions) of the tensor
print(f"Data type of the tensor: {randtens.dtype}")  # Returns the data type of the tensor
print(f"Number of dimensions (rank): {randtens.ndim}")  # Returns the number of dimensions (rank) of the tensor
print(f"Number of elements in the tensor: {tf.size(randtens)}")  # Returns the total number of elements in the tensor
print(f"Device (CPU/GPU): {tensor.device}")  # Shows if the tensor is on CPU or GPU

Shape of the tenso: (3, 2)
Data type of the tensor: <dtype: 'float32'>
Number of dimensions (rank): 2
Number of elements in the tensor: 6
Device (CPU/GPU): /job:localhost/replica:0/task:0/device:CPU:0


### Extract Values From a Tensor

In [54]:
# convert tensor to a numpy array
# it can be useful for visualization and further manipulation
numpy_array = randtens.numpy()  # Works in TensorFlow

In [56]:
# extract a single value
value1 = randtens[0, 0].numpy()
value2 = randtens.numpy().item()
value1, value2

ValueError: can only convert an array of size 1 to a Python scalar

**NOTE!** `randtens.numpy().item()` works fine only if the tensor has one single element.

In [57]:
# convert tensor toa python list
randtens.numpy().tolist()

[[0.32746851444244385, -0.8426257967948914],
 [0.31943368911743164, -1.407551884651184],
 [-2.3880598545074463, -1.0392478704452515]]

### Get Statistical Information

In [63]:
print(f"Minimum value: {tf.reduce_min(randtens)}")
print(f"Maximum value: {tf.reduce_max(randtens.numpy())}")
print(f"Mean value: {tf.reduce_mean(randtens)}")
print(f"Sum value: {tf.reduce_sum(randtens)}")
print(f"Standard deviation value: {tf.math.reduce_std(tf.cast(randtens, dtype=tf.float32))}")
print(f"Variance value: {tf.math.reduce_variance(tf.cast(randtens, dtype=tf.float32))}")
print(f"Median value: {tf.math.reduce_variance(tf.cast(randtens, dtype=tf.float32))}")
print(f"Product value: {tf.math.reduce_prod(randtens)}")
print(f"Argmax value: {tf.math.argmax(randtens)}")
print(f"Argmin value: {tf.math.argmin(randtens)}")
print(f"Unique values: {tf.unique(A)}")  # it only wirks with a 1D vector
print(f"Unique values and their counts: {tf.unique_with_counts(A)}")

Minimum value: -2.3880598545074463
Maximum value: 0.32746851444244385
Mean value: -0.8384305834770203
Sum value: -5.030583381652832
Standard deviation value: 0.9544252157211304
Variance value: 0.9109275341033936
Median value: 0.9109275341033936
Product value: 0.30790290236473083
Argmax value: [0 0]
Argmin value: [2 1]
Unique values: Unique(y=<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>, idx=<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>)
Unique values and their counts: UniqueWithCounts(y=<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>, idx=<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7, 

### Summary of All Methods Together

| Method                  | Description                                                      |
|:------------------------|:-----------------------------------------------------------------|
| tf.constant             | Creates a constant tensor.                                       |
| tf.Variable             | Creates a mutable tensor (variable).                             |
| tf.random.normal        | Creates a tensor with random values from a normal distribution.  |
| tf.random.uniform       | Creates a tensor with random values from a uniform distribution. |
| tf.random.set_seed      | Sets the random seed for reproducibility.                        |
| tf.random.shuffle       | Shuffles the elements of a tensor.                               |
| tf.zeros                | Creates a tensor filled with zeros.                              |
| tf.ones                 | Creates a tensor filled with ones.                               |
| tf.fill                 | Creates a tensor filled with a specific value.                   |
| tf.range                | Creates a tensor with a sequence of numbers.                     |
| tf.linspace             | Creates a tensor with linearly spaced values.                    |
| tf.eye                  | Creates an identity matrix.                                      |
| tf.reduce_min           | Computes the minimum value of a tensor.                          |
| tf.reduce_max           | Computes the maximum value of a tensor.                          |
| tf.reduce_mean          | Computes the mean value of a tensor.                             |
| tf.reduce_sum           | Computes the sum of elements in a tensor.                        |
| tf.math.reduce_std      | Computes the standard deviation of a tensor.                     |
| tf.math.reduce_variance | Computes the variance of a tensor.                               |
| tf.math.reduce_prod     | Computes the product of elements in a tensor.                    |
| tf.math.argmax          | Returns the index of the maximum value in a tensor.              |
| tf.math.argmin          | Returns the index of the minimum value in a tensor.              |
| tf.unique               | Finds the unique elements in a tensor.                           |
| tf.unique_with_counts   | Finds the unique elements in a tensor along with their counts.   |
| assign                  | Updates the variable in place.                                   |
| assign_add              | Adds a value to each element of the variable in place.           |
| numpy                   | Convert tensor to numpy array                                    |
| tolist                  | Convert tensor to a python list                                  |
| item                    | Extract value from a tensor                                      |

### Get Specific Elements Using Indexing

In [65]:
print(randtens[0])      # First row
print(randtens[:, 1])   # Second column

tf.Tensor([ 0.3274685 -0.8426258], shape=(2,), dtype=float32)
tf.Tensor([-0.8426258 -1.4075519 -1.0392479], shape=(3,), dtype=float32)


## Advanced Topics in TensorFlow
- 🚀 Custom Training Loops – Use tf.GradientTape for advanced model training.
- 🚀 Transfer Learning – Use pre-trained models from tf.keras.applications.
- 🚀 Distributed Training – Train across multiple GPUs or TPUs with tf.distribute.Strategy.
- 🚀 TensorFlow Hub – Import pre-trained models for fine-tuning.